"""add pitch id to db

Revision ID: c72af7616c41
Revises: e581d0683214
Create Date: 2021-06-13 13:36:44.798741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72af7616c41'
down_revision = 'e581d0683214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_id')
    # ### end Alembic commands ###
